language: java

install:
  - git clone https://github.com/martylamb/nailgun.git
  - cd nailgun/nailgun-server && mvn install -Dmaven.javadoc.skip=true && cd ../../

script:
  - cd assistant && mvn package && cd ..
