language: java
jdk: oraclejdk8
before_install:
  - sudo apt-get -qq -y install zsh
install:
  # this currently missing a bugfix, but should be returned to original author when pr merged
  #- git clone https://github.com/manouti/jar-timestamp-normalize-maven-plugin.git norm && cd norm && mvn install && cd ..
  - (git clone https://github.com/automaticgiant/jar-timestamp-normalize-maven-plugin.git norm && cd norm && mvn -T 2 install)
  - (cd nailgun-git/nailgun-server && mvn -T 2 install -Dmaven.javadoc.skip=true)
script:
  - (cd assistant && mvn -T 2 package)
  - (zsh test.zsh)
before_deploy:
  - sh before_deploy.sh
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIAJHKY3MT3JTDDUEJA
  secret_access_key:
    secure: dhvNXSDgJb1grUuA31MkuqeU2ym0E8DjjLKM73Jnxi6Sy5Uy0KYeTXE5ceRNw1itJD81naSADP75lSgy4y0oSwYPJhuz6DHibrLKj2CIn2EC7Debch4iM1Ehcs/GFAzlEwu9lV+CsZBalMGuwmrUnHr7JMTqrAdVHfM5msJxiTlp8tnefvIEyGsZXccCRBkk7UigiK9NhT+rE9SjXxRqVKpSppb7knZ3mZcbD51XMwRIIIdi7Qsf36IES6me+W133lia7HuN4V2cw5AlaCORqBqi8ji9HUDLwZC1MQrdbnhV33dcqGWfbQ3+4V93LVmoc/5pIq1+HzZ3HoxEoYqzLOu3Mo8DngTyN12yd+pNUYZRxSvtNrJ4YOn/ghWkPRfshfhUmGTyobXDEI9xNk51thaGJbBOukX6STBVCKpUwlusgbcSJHAG5fMey5xhtqW/XAhmHvwJAKPjpy+bct9OcmVqW9vseCKMWdcfGq7g4mXppv4XpKfGfwp/arKwDCyjQtFl+HPcEunSdNMPSKWBt28im39imnlvqJqpKs6UbUJ3zkikAUHtI60+T2xUuxSLPpAr/6IX/VUIyZGcaHMWAzwF6XWgVOPK8J3ZpCFpRS8x6aIq3SfnJG7kYFySFC8vICtCcjsocgoWNgveYhHf3RNaAgl//Yw0caP1tgrvoCE=
  bucket: valet2k
  local-dir: deploy
  upload-dir: builds
  acl: public_read
  on:
    repo: valet2k/logging
cache:
  directories:
  - $HOME/.m2
